# Read dummy verilog
read_verilog top.v


# Link part (typically autogenerated).
source autogen/link.tcl

# Read the constraint
read_xdc proj.xdc

# Basic synth
synth_design -top top

# Skip optimization, just place.
place_design

# Disable pesky DRC checks
set_property IS_ENABLED 0 [get_drc_checks {NSTD-1}];
set_property IS_ENABLED 0 [get_drc_checks {UCIO-1}];
set_property IS_ENABLED 0 [get_drc_checks {CFGBVS-1}];

# Route
route_design

# Write Bitstream (again, usually autogenerated)
source autogen/bitgen.tcl
